### ISSUE TITLE
error log when loading html from local resource streaming folder

### ISSUE THREAD

**Issue by tomtomtong** [vuplex/unity-html-ui-example#1]
[Web Console] Access to XMLHttpRequest at 'file:///D:/UnityProjects/Planetarium/Assets/StreamingAssets/eCampaign/assets/images/share/hires/intro_mr_eat.json' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, client, chrome-untrusted, https. (file:///D:/UnityProjects/Planetarium/Assets/StreamingAssets/eCampaign/Game01.html:0)
UnityEngine.Debug:LogError (object)

Hello. Your plugin is really great. But how could I solve this issue?

**Comment by binarynate** [comment]
Hi, @tomtomtong 👋. Thank you for using 3D WebView and for your kind words! Are you encountering this issue on Windows and macOS? If so, you may be able to disable the error by passing the --disable-web-security argument to Chromium with [StandaloneWebView.SetCommandLineArguments()](https://developer.vuplex.com/webview/StandaloneWebView#SetCommandLineArguments) like this:

```
void Awake() {
    #if UNITY_STANDALONE
        StandaloneWebView.SetCommandLineArguments("--disable-web-security");
    #endif
}
```

Also, for future support questions, please contact me [via this page](https://support.vuplex.com/contact). I will respond to those requests much faster, since this repo is just intended for the Unity HTML UI Example project.

**Comment by tomtomtong** [comment]
@binarynate Thank you. It really works. I will ask in the page you provided in the future.

**Comment by binarynate** [comment]
You're welcome, @tomtomtong! If this was helpful, can you please do me a favor and take a few seconds to rate 3D WebView on the Asset Store? It would have a big impact because it doesn't have many ratings, and it would mean a lot to me:

[Rate 3D WebView for Windows and macOS on the Asset Store](https://assetstore.unity.com/packages/tools/gui/3d-webview-for-windows-and-macos-web-browser-154144#reviews)

Thanks!
